-- Create rsvps table for the wedding invitation project
CREATE TABLE IF NOT EXISTS public.rsvps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    contact TEXT NOT NULL,
    attending BOOLEAN NOT NULL,
    guest_count INTEGER NOT NULL DEFAULT 1,
    meal_preference TEXT,
    message TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.rsvps ENABLE ROW LEVEL SECURITY;

-- Allow public (anon) insert access so guests can submit RSVP from the website
DROP POLICY IF EXISTS "Allow public insert for rsvps" ON public.rsvps;
CREATE POLICY "Allow public insert for rsvps" 
ON public.rsvps 
FOR INSERT 
TO public 
WITH CHECK (true);

-- Allow authenticated users to read RSVP entries
DROP POLICY IF EXISTS "Allow authenticated read for rsvps" ON public.rsvps;
CREATE POLICY "Allow authenticated read for rsvps" 
ON public.rsvps 
FOR SELECT 
TO authenticated 
USING (true);
